server:
  port: 3344
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yang472312760/cloud-config.git
          search-paths:
            - cloud-config
        label: main
  rabbitmq:
    host: 192.168.220.128
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
eureka:
  client:
    service-url:
      defaultZone:  http://192.168.220.128:7001/eureka