server:
  port: 80


spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: 192.168.220.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}

service-url:
  consul-consumer-service: http://consul-provider
