server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java