server:
  port: 80

eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.220.128:7001/eureka/
  instance:
    prefer-ip-address: true
#  server:
#    enable-self-preservation: false
spring:
  application:
    name: cloud-hystrix-consumer
#    eviction-interval-timer-in-ms: 2000
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。