server:
  port: 8006


spring:
  application:
    name: consul-provider
  cloud:
    consul:
      host: 192.168.220.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}


